version: '3'
services:
  # アプリケーションに関する記述
  app:
    build:
      context: ./
      dockerfile: ./Docker/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      # ローカルのフォルダ「src」にマウント
      - ./src:/app
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db
  # DBに関する記述（PostgreSQLの場合）
  db:
    # 2022年5月26日時点の最新版
    image: postgres:14.3
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # コンテナの中身を保存しておくために作成したボリュームでマウント
    volumes:
      - db-data:/var/lib/postgresql/data
  # Webサーバーに関する記述
  web:
    build:
      context: ./
      dockerfile: ./Docker/nginx/Dockerfile
    volumes:
      # コンテナの中身を保存しておくために作成したボリュームでマウント
      - ./src/:/app
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    # app起動後にwebを起動させる設定（依存関係）
    depends_on:
      - app

volumes:
  db-data: